Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Get-RepoRoot {
    $current = Get-Location
    while ($null -ne $current) {
        $gitPath = [System.IO.Path]::Combine($current.Path, '.git')
        $slnPath = [System.IO.Path]::Combine($current.Path, 'MigrationBaseSolution.sln')
        if ((Test-Path -LiteralPath $gitPath) -or (Test-Path -LiteralPath $slnPath -PathType Leaf)) {
            return $current.Path
        }
        $current = $current.Parent
    }
    throw 'Unable to locate repository root. Run this script from inside the MigrationBaseSolution repository.'
}

function Ensure-Directory {
    param([Parameter(Mandatory=$true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Get-RelativePath {
    param(
        [Parameter(Mandatory=$true)][string]$BasePath,
        [Parameter(Mandatory=$true)][string]$FullPath
    )
    $base = [System.IO.Path]::GetFullPath($BasePath).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $full = [System.IO.Path]::GetFullPath($FullPath)
    $baseUri = New-Object System.Uri(($base + [System.IO.Path]::DirectorySeparatorChar))
    $fullUri = New-Object System.Uri($full)
    $relative = $baseUri.MakeRelativeUri($fullUri).ToString()
    return [System.Uri]::UnescapeDataString($relative).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

function Write-Report {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][object[]]$Entries
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# P10.2AQ Local Apply Report') | Out-Null
    $lines.Add('') | Out-Null
    $lines.Add('Generated by Apply-P10.2AQ-AdminWebAppsResidualBatchCopy.ps1.') | Out-Null
    $lines.Add('') | Out-Null
    $lines.Add('| Action | Family | Relative Path |') | Out-Null
    $lines.Add('|---|---|---|') | Out-Null
    foreach ($entry in $Entries) {
        $lines.Add(('| {0} | {1} | `{2}` |' -f $entry.Action, $entry.Family, $entry.RelativePath.Replace('\', '/'))) | Out-Null
    }
    if ($Entries.Count -eq 0) {
        $lines.Add('| None | None | No residual app source files required copying. |') | Out-Null
    }
    Set-Content -LiteralPath $Path -Value $lines -Encoding UTF8
}

$repoRoot = Get-RepoRoot
$appsSourceRoot = [System.IO.Path]::Combine($repoRoot, 'apps', 'migration-admin-ui', 'src')
$adminSourceRoot = [System.IO.Path]::Combine($repoRoot, 'src', 'Admin', 'Migration.Admin.Web', 'src')
$reportPath = [System.IO.Path]::Combine($repoRoot, 'docs', 'P10', 'P10.2AQ-AdminWebAppsResidualBatchCopy.LocalReport.md')

if (-not (Test-Path -LiteralPath $appsSourceRoot -PathType Container)) {
    throw ('Reference app source root not found: {0}' -f $appsSourceRoot)
}
if (-not (Test-Path -LiteralPath $adminSourceRoot -PathType Container)) {
    throw ('Canonical Admin Web source root not found: {0}' -f $adminSourceRoot)
}

$families = @(
    [pscustomobject]@{ Name = 'features' },
    [pscustomobject]@{ Name = 'components' },
    [pscustomobject]@{ Name = 'auth' },
    [pscustomobject]@{ Name = 'lib' }
)

$entries = @()
foreach ($family in $families) {
    $sourceFamilyRoot = [System.IO.Path]::Combine($appsSourceRoot, $family.Name)
    $targetFamilyRoot = [System.IO.Path]::Combine($adminSourceRoot, $family.Name)
    if (-not (Test-Path -LiteralPath $sourceFamilyRoot -PathType Container)) {
        $entries += [pscustomobject]@{ Action = 'MissingInApps'; Family = $family.Name; RelativePath = $family.Name }
        continue
    }
    Ensure-Directory -Path $targetFamilyRoot
    $files = @(Get-ChildItem -LiteralPath $sourceFamilyRoot -Recurse -File | Sort-Object FullName)
    foreach ($file in $files) {
        $relative = Get-RelativePath -BasePath $sourceFamilyRoot -FullPath $file.FullName
        $targetPath = [System.IO.Path]::Combine($targetFamilyRoot, $relative)
        $targetDirectory = [System.IO.Path]::GetDirectoryName($targetPath)
        Ensure-Directory -Path $targetDirectory
        if (Test-Path -LiteralPath $targetPath -PathType Leaf) {
            $entries += [pscustomobject]@{ Action = 'SkippedExisting'; Family = $family.Name; RelativePath = ([System.IO.Path]::Combine($family.Name, $relative)) }
            continue
        }
        Copy-Item -LiteralPath $file.FullName -Destination $targetPath
        $entries += [pscustomobject]@{ Action = 'Copied'; Family = $family.Name; RelativePath = ([System.IO.Path]::Combine($family.Name, $relative)) }
    }
}

$reportDirectory = [System.IO.Path]::GetDirectoryName($reportPath)
Ensure-Directory -Path $reportDirectory
Write-Report -Path $reportPath -Entries $entries
Write-Host ('P10.2AQ residual app source batch copy completed. Report: {0}' -f $reportPath)
