using Migration.ControlPlane.Artifacts;
using Migration.ControlPlane.ManifestBuilder;

namespace Migration.Admin.Api.Endpoints;

public static class ManifestBuilderEndpoints
{
    public static IEndpointRouteBuilder MapManifestBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/manifest-builder")
            .WithTags("Manifest Builder");

        group.MapGet("/sources", (ManifestBuilderServiceRegistry registry) =>
            {
                return Results.Ok(registry.GetSources());
            })
            .WithName("GetManifestBuilderSources")
            .WithSummary("Lists source connectors and services that can generate manifest artifacts.");

        group.MapPost("/build", async (
                BuildSourceManifestRequest request,
                ManifestBuilderServiceRegistry registry,
                IArtifactStore artifacts,
                CancellationToken cancellationToken) =>
            {
                if (string.IsNullOrWhiteSpace(request.SourceType))
                {
                    return Results.BadRequest(new { error = "SourceType is required." });
                }

                if (string.IsNullOrWhiteSpace(request.ServiceName))
                {
                    return Results.BadRequest(new { error = "ServiceName is required." });
                }

                var service = registry.TryGetService(request.SourceType, request.ServiceName);
                if (service is null)
                {
                    return Results.BadRequest(new
                    {
                        error = $"No manifest builder service is registered for source '{request.SourceType}' and service '{request.ServiceName}'."
                    });
                }

                BuildSourceManifestResult result;
                try
                {
                    result = await service.BuildAsync(request, cancellationToken).ConfigureAwait(false);
                }
                catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
                {
                    return Results.BadRequest(new { error = ex.Message });
                }
                catch (TaskCanceledException ex) when (!cancellationToken.IsCancellationRequested)
                {
                    return Results.Problem(
                        title: "Manifest build timed out.",
                        detail: ex.Message,
                        statusCode: StatusCodes.Status504GatewayTimeout);
                }

                var contentType = string.IsNullOrWhiteSpace(result.ContentType)
                    ? "application/octet-stream"
                    : result.ContentType;

                await using var stream = CreateManifestContentStream(result);

                var artifact = await artifacts.SaveAsync(
                        stream,
                        result.FileName,
                        contentType,
                        ArtifactKind.Manifest,
                        projectId: null,
                        description: $"Generated by Manifest Builder from {result.SourceType}/{result.ServiceName}",
                        metadata: new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                        {
                            ["sourceType"] = result.SourceType,
                            ["serviceName"] = result.ServiceName,
                            ["rowCount"] = result.RowCount.ToString(System.Globalization.CultureInfo.InvariantCulture)
                        },
                        cancellationToken: cancellationToken)
                    .ConfigureAwait(false);

                var downloadUrl = $"/api/artifacts/{Uri.EscapeDataString(artifact.ArtifactId)}/download";

                return Results.Created(
                    $"/api/artifacts/{Uri.EscapeDataString(artifact.ArtifactId)}",
                    new BuildSourceManifestResponse(
                        artifact.ArtifactId,
                        artifact.ArtifactId,
                        result.SourceType,
                        result.ServiceName,
                        artifact.FileName,
                        artifact.ContentType,
                        result.RowCount,
                        downloadUrl,
                        artifact.CreatedUtc));
            })
            .WithName("BuildSourceManifest")
            .WithSummary("Runs a source manifest service, saves the generated file as a Manifest artifact, and returns only artifact metadata.");

        return app;
    }

    private static MemoryStream CreateManifestContentStream(BuildSourceManifestResult result)
    {
        if (result.ContentBytes is { Length: > 0 })
        {
            return new MemoryStream(result.ContentBytes, writable: false);
        }

        var content = result.Content ?? string.Empty;
        return new MemoryStream(System.Text.Encoding.UTF8.GetBytes(content), writable: false);
    }
}
