using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;
using Migration.Connectors.Targets.Bynder.Taxonomy;
using Migration.Connectors.Targets.Aprimo.Workbooks;
using Migration.ControlPlane.Artifacts;
using Migration.ControlPlane.Models;
using Migration.ControlPlane.Services;

namespace Migration.Admin.Api.Endpoints;

public static class TaxonomyBuilderEndpoints
{
    private static readonly HttpClient Http = new();
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web) { WriteIndented = true };

    public static IEndpointRouteBuilder MapTaxonomyBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/taxonomy-builder")
            .WithTags("Taxonomy Builder");

        group.MapPost("/build", async (
            BuildTaxonomyArtifactRequest request,
            ICredentialSetStore credentialStore,
            IArtifactStore artifactStore,
            ILoggerFactory loggerFactory,
            IConfiguration configuration,
            BynderTaxonomyWorkbookBuilder bynderTaxonomyWorkbookBuilder,
            CancellationToken cancellationToken) =>
        {
            var validation = await ValidateAsync(request, credentialStore, cancellationToken).ConfigureAwait(false);
            if (validation.Result is not null)
            {
                return validation.Result;
            }

            var credential = validation.Credential!;
            var targetKind = validation.TargetKind!;

            try
            {
                if (targetKind == "aprimo")
                {
                    return await BuildAprimoConfigurationWorkbookAsync(request, credential, artifactStore, loggerFactory, cancellationToken).ConfigureAwait(false);
                }

                if (targetKind == "bynder")
                {
                    return await BuildBynderMetadataPropertiesWorkbookAsync(
                        request,
                        credential,
                        artifactStore,
                        configuration,
                        bynderTaxonomyWorkbookBuilder,
                        cancellationToken).ConfigureAwait(false);
                }

                var snapshot = targetKind switch
                {
                    "cloudinary" => await ReadCloudinaryTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    _ => throw new InvalidOperationException($"Unsupported taxonomy target '{request.TargetType}'.")
                };

                var workbookXml = BuildLegacyWorkbookXml(snapshot, request.IncludeOptions, request.IncludeRaw);
                await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(workbookXml));
                var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName)
                    ? $"{targetKind}-taxonomy-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xls"
                    : request.FileName.Trim());
                if (!fileName.EndsWith(".xls", StringComparison.OrdinalIgnoreCase))
                {
                    fileName = Path.ChangeExtension(fileName, ".xls");
                }

                var artifact = await artifactStore.SaveAsync(
                    stream,
                    fileName,
                    "application/vnd.ms-excel",
                    ArtifactKind.Taxonomy,
                    request.ProjectId,
                    string.IsNullOrWhiteSpace(request.Description)
                        ? $"Generated by Taxonomy Builder from {snapshot.TargetType}"
                        : request.Description,
                    MetadataFor(request, credential, snapshot.TargetType, snapshot.Fields.Count, snapshot.Options.Count, "TaxonomyWorkbook"),
                    cancellationToken).ConfigureAwait(false);

                return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
                    new BuildTaxonomyArtifactResponse(artifact, snapshot.TargetType, snapshot.Fields.Count, snapshot.Options.Count, artifact.FileName));
            }
            catch (Exception ex) when (ex is InvalidOperationException or HttpRequestException or JsonException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }
        })
        .WithSummary("Pull target metadata schema and save it as an Excel taxonomy artifact.");

        group.MapPost("/blank-template", async (
            BuildTaxonomyArtifactRequest request,
            ICredentialSetStore credentialStore,
            IArtifactStore artifactStore,
            ILoggerFactory loggerFactory,
            IConfiguration configuration,
            BynderTaxonomyWorkbookBuilder bynderTaxonomyWorkbookBuilder,
            CancellationToken cancellationToken) =>
        {
            var validation = await ValidateAsync(request, credentialStore, cancellationToken).ConfigureAwait(false);
            if (validation.Result is not null)
            {
                return validation.Result;
            }

            var credential = validation.Credential!;
            var targetKind = validation.TargetKind!;

            try
            {
                if (targetKind == "aprimo")
                {
                    return await BuildAprimoBlankMetadataTemplateAsync(request, credential, artifactStore, loggerFactory, cancellationToken).ConfigureAwait(false);
                }

                if (targetKind == "bynder")
                {
                    return await BuildBynderBlankMetadataTemplateAsync(
                        request,
                        credential,
                        artifactStore,
                        configuration,
                        bynderTaxonomyWorkbookBuilder,
                        cancellationToken).ConfigureAwait(false);
                }

                var snapshot = targetKind switch
                {
                    "cloudinary" => await ReadCloudinaryTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    _ => throw new InvalidOperationException($"Unsupported taxonomy target '{request.TargetType}'.")
                };

                var workbookXml = BuildBlankMetadataTemplateXml(snapshot);
                await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(workbookXml));
                var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName)
                    ? $"{targetKind}-blank-metadata-template-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xls"
                    : request.FileName.Trim());
                if (!fileName.EndsWith(".xls", StringComparison.OrdinalIgnoreCase))
                {
                    fileName = Path.ChangeExtension(fileName, ".xls");
                }

                var artifact = await artifactStore.SaveAsync(
                    stream,
                    fileName,
                    "application/vnd.ms-excel",
                    ArtifactKind.Taxonomy,
                    request.ProjectId,
                    string.IsNullOrWhiteSpace(request.Description)
                        ? $"Generated blank metadata template from {snapshot.TargetType} taxonomy"
                        : request.Description,
                    MetadataFor(request, credential, snapshot.TargetType, snapshot.Fields.Count, snapshot.Options.Count, "BlankMetadataTemplate"),
                    cancellationToken).ConfigureAwait(false);

                return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
                    new BuildTaxonomyArtifactResponse(artifact, snapshot.TargetType, snapshot.Fields.Count, snapshot.Options.Count, artifact.FileName));
            }
            catch (Exception ex) when (ex is InvalidOperationException or HttpRequestException or JsonException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }
        })
        .WithSummary("Build a blank metadata workbook template from target metadata fields.");

        return app;
    }

    private static async Task<(IResult? Result, CredentialSetRecord? Credential, string? TargetKind)> ValidateAsync(
        BuildTaxonomyArtifactRequest request,
        ICredentialSetStore credentialStore,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.TargetType))
        {
            return (Results.BadRequest(new { error = "targetType is required." }), null, null);
        }

        if (string.IsNullOrWhiteSpace(request.CredentialSetId))
        {
            return (Results.BadRequest(new { error = "credentialSetId is required." }), null, null);
        }

        var credential = await credentialStore.GetAsync(request.CredentialSetId, cancellationToken).ConfigureAwait(false);
        if (credential is null)
        {
            return (Results.NotFound(new { error = $"Credential set '{request.CredentialSetId}' was not found." }), null, null);
        }

        if (!string.Equals(credential.ConnectorRole, "target", StringComparison.OrdinalIgnoreCase))
        {
            return (Results.BadRequest(new { error = "Taxonomy Builder requires a target credential set." }), null, null);
        }

        var targetKind = NormalizeTargetKind(request.TargetType);
        if (targetKind is null)
        {
            return (Results.BadRequest(new { error = "Taxonomy Builder currently supports Bynder, Cloudinary, and Aprimo targets." }), null, null);
        }

        return (null, credential, targetKind);
    }

    private static async Task<IResult> BuildAprimoConfigurationWorkbookAsync(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        IArtifactStore artifactStore,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var credentials = BuildAprimoCredentials(credential);
        var service = new AprimoConfigurationWorkbookService(new HttpClient(), loggerFactory.CreateLogger<AprimoConfigurationWorkbookService>());
        await using var stream = new MemoryStream();

        var result = await service.GenerateAsync(
            new AprimoConfigurationWorkbookRequest(credentials, AprimoConfigurationWorkbookExportOptions.Defaults),
            stream,
            cancellationToken).ConfigureAwait(false);

        stream.Position = 0;
        var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName) ? result.FileName : request.FileName.Trim());
        if (!fileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            fileName = Path.ChangeExtension(fileName, ".xlsx");
        }

        var artifact = await artifactStore.SaveAsync(
            stream,
            fileName,
            result.ContentType,
            ArtifactKind.Taxonomy,
            request.ProjectId,
            string.IsNullOrWhiteSpace(request.Description)
                ? "Generated by Taxonomy Builder from Aprimo configuration workbook service"
                : request.Description,
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["GeneratedBy"] = "TaxonomyBuilder",
                ["TargetType"] = "Aprimo",
                ["CredentialSetId"] = credential.CredentialSetId,
                ["WorksheetCount"] = result.WorksheetCount.ToString(CultureInfo.InvariantCulture),
                ["WorkbookKind"] = "AprimoConfigurationWorkbook"
            },
            cancellationToken).ConfigureAwait(false);

        var fieldCount = result.RowCounts.TryGetValue("Field definitions", out var fields) ? fields : 0;
        return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
            new BuildTaxonomyArtifactResponse(artifact, "Aprimo", fieldCount, 0, artifact.FileName));
    }

    private static async Task<IResult> BuildAprimoBlankMetadataTemplateAsync(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        IArtifactStore artifactStore,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var credentials = BuildAprimoCredentials(credential);
        var service = new AprimoMetadataTemplateWorkbookService(new HttpClient(), loggerFactory.CreateLogger<AprimoMetadataTemplateWorkbookService>());
        await using var stream = new MemoryStream();

        var result = await service.GenerateAsync(credentials, stream, cancellationToken).ConfigureAwait(false);

        stream.Position = 0;
        var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName) ? result.FileName : request.FileName.Trim());
        if (!fileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            fileName = Path.ChangeExtension(fileName, ".xlsx");
        }

        var artifact = await artifactStore.SaveAsync(
            stream,
            fileName,
            result.ContentType,
            ArtifactKind.Taxonomy,
            request.ProjectId,
            string.IsNullOrWhiteSpace(request.Description)
                ? "Generated blank Aprimo metadata template from field definitions"
                : request.Description,
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["GeneratedBy"] = "TaxonomyBuilder",
                ["TargetType"] = "Aprimo",
                ["CredentialSetId"] = credential.CredentialSetId,
                ["WorkbookKind"] = "AprimoBlankMetadataTemplate",
                ["FieldCount"] = result.FieldCount.ToString(CultureInfo.InvariantCulture),
                ["ColumnCount"] = result.ColumnCount.ToString(CultureInfo.InvariantCulture)
            },
            cancellationToken).ConfigureAwait(false);

        return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
            new BuildTaxonomyArtifactResponse(artifact, "Aprimo", result.FieldCount, 0, artifact.FileName));
    }

    private static AprimoConfigurationWorkbookCredentials BuildAprimoCredentials(CredentialSetRecord credential)
    {
        var subDomain = FirstValue(credential.Values, "subDomain", "SubDomain", "aprimoSubDomain", "AprimoSubDomain", "tenant", "Tenant", "tenantName", "TenantName");
        var baseUrl = FirstValue(credential.Values, "baseUrl", "BaseUrl", "url", "Url", "tenantUrl", "TenantUrl", "aprimoBaseUrl", "AprimoBaseUrl");
        var clientId = FirstValue(credential.Values, "clientId", "ClientId", "aprimoClientId", "AprimoClientId", "TargetCredential_ClientId");
        var clientSecret = FirstValue(credential.Values, "clientSecret", "ClientSecret", "aprimoClientSecret", "AprimoClientSecret", "secret", "Secret", "TargetCredential_ClientSecret");

        if (string.IsNullOrWhiteSpace(subDomain) && !string.IsNullOrWhiteSpace(baseUrl))
        {
            subDomain = TryExtractSubDomain(baseUrl) ?? string.Empty;
        }

        if (string.IsNullOrWhiteSpace(subDomain))
        {
            throw new InvalidOperationException("Aprimo workbook generation requires a subDomain, aprimoSubDomain, tenant, or Aprimo baseUrl that contains the subdomain.");
        }

        if (string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret))
        {
            throw new InvalidOperationException("Aprimo workbook generation requires clientId and clientSecret credentials.");
        }

        return new AprimoConfigurationWorkbookCredentials(subDomain, clientId, clientSecret, string.IsNullOrWhiteSpace(baseUrl) ? null : baseUrl);
    }

    private static async Task<IResult> BuildBynderMetadataPropertiesWorkbookAsync(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        IArtifactStore artifactStore,
        IConfiguration configuration,
        BynderTaxonomyWorkbookBuilder bynderTaxonomyWorkbookBuilder,
        CancellationToken cancellationToken)
    {
        var credentials = await BuildBynderOAuthCredentialsAsync(credential, configuration, cancellationToken).ConfigureAwait(false);
        var result = await bynderTaxonomyWorkbookBuilder.BuildMetadataPropertiesWorkbookAsync(
            credentials.BaseUrl,
            credentials.ClientId,
            credentials.ClientSecret,
            credentials.Scopes,
            cancellationToken).ConfigureAwait(false);

        await using var stream = result.Stream;
        var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName)
            ? $"bynder-metadata-properties-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xlsx"
            : request.FileName.Trim());
        if (!fileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            fileName = Path.ChangeExtension(fileName, ".xlsx");
        }

        var artifact = await artifactStore.SaveAsync(
            stream,
            fileName,
            BynderTaxonomyWorkbookBuilder.MetadataPropertiesContentType,
            ArtifactKind.Taxonomy,
            request.ProjectId,
            string.IsNullOrWhiteSpace(request.Description)
                ? "Generated by Taxonomy Builder from Bynder connector metadata properties workbook builder"
                : request.Description,
            MetadataFor(request, credential, "Bynder", result.FieldCount, result.OptionCount, result.WorkbookKind),
            cancellationToken).ConfigureAwait(false);

        return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
            new BuildTaxonomyArtifactResponse(artifact, "Bynder", result.FieldCount, result.OptionCount, artifact.FileName));
    }

    private static async Task<IResult> BuildBynderBlankMetadataTemplateAsync(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        IArtifactStore artifactStore,
        IConfiguration configuration,
        BynderTaxonomyWorkbookBuilder bynderTaxonomyWorkbookBuilder,
        CancellationToken cancellationToken)
    {
        var credentials = await BuildBynderOAuthCredentialsAsync(credential, configuration, cancellationToken).ConfigureAwait(false);
        var result = await bynderTaxonomyWorkbookBuilder.BuildBlankMetadataTemplateWorkbookAsync(
            credentials.BaseUrl,
            credentials.ClientId,
            credentials.ClientSecret,
            credentials.Scopes,
            cancellationToken).ConfigureAwait(false);

        await using var stream = result.Stream;
        var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName)
            ? $"bynder-blank-metadata-template-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xlsx"
            : request.FileName.Trim());
        if (!fileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            fileName = Path.ChangeExtension(fileName, ".xlsx");
        }

        var artifact = await artifactStore.SaveAsync(
            stream,
            fileName,
            BynderTaxonomyWorkbookBuilder.MetadataPropertiesContentType,
            ArtifactKind.Taxonomy,
            request.ProjectId,
            string.IsNullOrWhiteSpace(request.Description)
                ? "Generated blank metadata template from Bynder connector metadata properties workbook builder"
                : request.Description,
            MetadataFor(request, credential, "Bynder", result.FieldCount, result.OptionCount, result.WorkbookKind),
            cancellationToken).ConfigureAwait(false);

        return Results.Created($"/api/artifacts/{artifact.ArtifactId}",
            new BuildTaxonomyArtifactResponse(artifact, "Bynder", result.FieldCount, result.OptionCount, artifact.FileName));
    }

    private static async Task<BynderOAuthCredentials> BuildBynderOAuthCredentialsAsync(
        CredentialSetRecord credential,
        IConfiguration configuration,
        CancellationToken cancellationToken)
    {
        var baseUrl = await ResolveCredentialValueAsync(credential.Values, configuration, cancellationToken,
            "BaseUrl", "baseUrl", "BynderBaseUrl", "bynderBaseUrl", "url", "Url", "domain", "Domain", "bynderDomain", "BynderDomain").ConfigureAwait(false);
        var clientId = await ResolveCredentialValueAsync(credential.Values, configuration, cancellationToken,
            "ClientId", "clientId", "BynderClientId", "bynderClientId").ConfigureAwait(false);
        var clientSecret = await ResolveCredentialValueAsync(credential.Values, configuration, cancellationToken,
            "ClientSecret", "clientSecret", "BynderClientSecret", "bynderClientSecret").ConfigureAwait(false);
        var scopes = await ResolveCredentialValueAsync(credential.Values, configuration, cancellationToken,
            "Scopes", "scopes", "BynderScopes", "bynderScopes").ConfigureAwait(false);

        var missing = new List<string>();
        if (string.IsNullOrWhiteSpace(baseUrl)) missing.Add("BaseUrl");
        if (string.IsNullOrWhiteSpace(clientId)) missing.Add("ClientId");
        if (string.IsNullOrWhiteSpace(clientSecret)) missing.Add("ClientSecret");
        if (string.IsNullOrWhiteSpace(scopes)) missing.Add("Scopes");

        if (missing.Count > 0)
        {
            throw new InvalidOperationException(
                "Bynder taxonomy generation requires OAuth credential value(s): " +
                string.Join(", ", missing) +
                ". Expected BaseUrl, ClientId, ClientSecret, and Scopes from the selected Bynder target credential set.");
        }

        return new BynderOAuthCredentials(baseUrl!, clientId!, clientSecret!, scopes!);
    }

    private static async Task<string?> ResolveCredentialValueAsync(
        IReadOnlyDictionary<string, string> values,
        IConfiguration configuration,
        CancellationToken cancellationToken,
        params string[] keys)
    {
        var value = FirstValue(values, keys);
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        value = value.Trim();

        if (value.StartsWith("env://", StringComparison.OrdinalIgnoreCase))
        {
            var variableName = value.Substring("env://".Length).Trim();
            return string.IsNullOrWhiteSpace(variableName)
                ? value
                : Environment.GetEnvironmentVariable(variableName) ?? value;
        }

        if (value.StartsWith("kv://", StringComparison.OrdinalIgnoreCase))
        {
            var secretName = value.Substring("kv://".Length).Trim('/');
            return await ReadKeyVaultSecretByNameAsync(configuration, secretName, cancellationToken).ConfigureAwait(false);
        }

        if (value.StartsWith("keyvault://", StringComparison.OrdinalIgnoreCase))
        {
            var secretName = value.Substring("keyvault://".Length).Trim('/');
            return await ReadKeyVaultSecretByNameAsync(configuration, secretName, cancellationToken).ConfigureAwait(false);
        }

        if (Uri.TryCreate(value, UriKind.Absolute, out var secretUri)
            && secretUri.Host.EndsWith(".vault.azure.net", StringComparison.OrdinalIgnoreCase)
            && secretUri.AbsolutePath.Contains("/secrets/", StringComparison.OrdinalIgnoreCase))
        {
            return await ReadKeyVaultSecretByUriAsync(secretUri, cancellationToken).ConfigureAwait(false);
        }

        return value;
    }

    private static async Task<string> ReadKeyVaultSecretByNameAsync(
        IConfiguration configuration,
        string secretName,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(secretName))
        {
            throw new InvalidOperationException("Credential secret reference did not include a Key Vault secret name.");
        }

        var vaultUri = GetConfiguredKeyVaultUri(configuration);
        if (vaultUri is null)
        {
            throw new InvalidOperationException(
                "Credential value is a Key Vault reference, but no Key Vault URI is configured. Expected CredentialVault:KeyVaultUri, AzureKeyVault:VaultUri, or KeyVault:VaultUri.");
        }

        var client = new SecretClient(vaultUri, new DefaultAzureCredential());
        var response = await client.GetSecretAsync(secretName, cancellationToken: cancellationToken).ConfigureAwait(false);
        return response.Value.Value;
    }

    private static async Task<string> ReadKeyVaultSecretByUriAsync(Uri secretUri, CancellationToken cancellationToken)
    {
        var pathParts = secretUri.AbsolutePath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var secretIndex = Array.FindIndex(pathParts, x => string.Equals(x, "secrets", StringComparison.OrdinalIgnoreCase));
        if (secretIndex < 0 || secretIndex + 1 >= pathParts.Length)
        {
            throw new InvalidOperationException($"Key Vault secret URI '{secretUri}' does not contain a secret name.");
        }

        var vaultBase = new Uri($"{secretUri.Scheme}://{secretUri.Host}/");
        var secretName = pathParts[secretIndex + 1];
        var version = secretIndex + 2 < pathParts.Length ? pathParts[secretIndex + 2] : null;
        var client = new SecretClient(vaultBase, new DefaultAzureCredential());
        var response = string.IsNullOrWhiteSpace(version)
            ? await client.GetSecretAsync(secretName, cancellationToken: cancellationToken).ConfigureAwait(false)
            : await client.GetSecretAsync(secretName, version, cancellationToken).ConfigureAwait(false);
        return response.Value.Value;
    }

    private static Uri? GetConfiguredKeyVaultUri(IConfiguration configuration)
    {
        var value = configuration["CredentialVault:KeyVaultUri"]
            ?? configuration["AzureKeyVault:VaultUri"]
            ?? configuration["KeyVault:VaultUri"];

        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        return Uri.TryCreate(value.TrimEnd('/'), UriKind.Absolute, out var uri)
            ? uri
            : throw new InvalidOperationException($"Configured Key Vault URI '{value}' is not a valid absolute URI.");
    }

    private static async Task<TaxonomySnapshot> ReadCloudinaryTaxonomyAsync(CredentialSetRecord credential, BuildTaxonomyArtifactRequest request, CancellationToken cancellationToken)
    {
        var cloudName = FirstValue(credential.Values, "cloudName", "cloud_name");
        var apiKey = FirstValue(credential.Values, "apiKey", "api_key");
        var apiSecret = FirstValue(credential.Values, "apiSecret", "api_secret", "secret");
        if (string.IsNullOrWhiteSpace(cloudName) || string.IsNullOrWhiteSpace(apiKey) || string.IsNullOrWhiteSpace(apiSecret))
        {
            throw new InvalidOperationException("Cloudinary credentials require cloudName, apiKey, and apiSecret.");
        }

        using var httpRequest = new HttpRequestMessage(HttpMethod.Get, $"https://api.cloudinary.com/v1_1/{Uri.EscapeDataString(cloudName)}/metadata_fields");
        httpRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(
            "Basic",
            Convert.ToBase64String(Encoding.ASCII.GetBytes($"{apiKey}:{apiSecret}")));
        using var response = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
        var json = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException($"Cloudinary metadata fields request failed: {(int)response.StatusCode} {response.ReasonPhrase}.{Environment.NewLine}{json}");
        }

        var root = JsonNode.Parse(json) ?? new JsonObject();
        var fieldNodes = root is JsonObject rootObj && rootObj["metadata_fields"] is JsonArray arr
            ? arr
            : AsArray(root);
        var fields = fieldNodes.OfType<JsonObject>()
            .Select(obj => new TaxonomyField(
                Text(obj, "external_id", "id", "name"),
                Text(obj, "external_id", "name", "id"),
                Text(obj, "label", "display_name", "external_id", "name"),
                Text(obj, "type"),
                Bool(obj, "mandatory", "required"),
                Bool(obj, "multiple", "multiValue"),
                Text(obj, "description", "help_text"),
                obj.ToJsonString(JsonOptions)))
            .ToList();

        return new TaxonomySnapshot("Cloudinary", fields, new List<TaxonomyOption>(), json);
    }

    private static JsonArray AsArray(JsonNode node) => node as JsonArray ?? new JsonArray(node);

    private static string Text(JsonObject obj, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (obj[key] is JsonValue value && !string.IsNullOrWhiteSpace(value.ToString()))
            {
                return value.ToString();
            }
        }

        return string.Empty;
    }

    private static bool Bool(JsonObject obj, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (obj[key] is JsonValue value && bool.TryParse(value.ToString(), out var parsed))
            {
                return parsed;
            }
        }

        return false;
    }

    private static string FirstValue(IReadOnlyDictionary<string, string> values, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (values.TryGetValue(key, out var value)
                && !string.IsNullOrWhiteSpace(value)
                && value != "********")
            {
                return value.Trim();
            }
        }

        return string.Empty;
    }

    private static string? NormalizeTargetKind(string targetType)
    {
        var value = targetType.Trim().ToLowerInvariant();
        if (value.Contains("bynder")) return "bynder";
        if (value.Contains("cloudinary")) return "cloudinary";
        if (value.Contains("aprimo")) return "aprimo";
        return null;
    }

    private static string CombineUrl(string baseUrl, string path) => baseUrl.TrimEnd('/') + "/" + path.TrimStart('/');

    private static string? TryExtractSubDomain(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return null;
        }

        var value = url.Trim();
        if (!value.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
            && !value.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            value = "https://" + value;
        }

        if (!Uri.TryCreate(value, UriKind.Absolute, out var uri))
        {
            return null;
        }

        var host = uri.Host;
        if (host.EndsWith(".dam.aprimo.com", StringComparison.OrdinalIgnoreCase))
        {
            return host[..^".dam.aprimo.com".Length];
        }

        return host.EndsWith(".aprimo.com", StringComparison.OrdinalIgnoreCase)
            ? host[..^".aprimo.com".Length]
            : null;
    }

    private static Dictionary<string, string> MetadataFor(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        string targetType,
        int fieldCount,
        int optionCount,
        string workbookKind) => new(StringComparer.OrdinalIgnoreCase)
    {
        ["GeneratedBy"] = "TaxonomyBuilder",
        ["TargetType"] = targetType,
        ["CredentialSetId"] = credential.CredentialSetId,
        ["FieldCount"] = fieldCount.ToString(CultureInfo.InvariantCulture),
        ["OptionCount"] = optionCount.ToString(CultureInfo.InvariantCulture),
        ["WorkbookKind"] = workbookKind
    };

    private static string MakeSafeFileName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var safe = new string(value.Select(ch => invalid.Contains(ch) ? '_' : ch).ToArray());
        return string.IsNullOrWhiteSpace(safe) ? $"taxonomy-{Guid.NewGuid():N}.xlsx" : safe;
    }

    private static string BuildLegacyWorkbookXml(TaxonomySnapshot snapshot, bool includeOptions, bool includeRaw)
    {
        var sheets = new StringBuilder();
        sheets.Append("<html><body>");
        sheets.Append(Worksheet("Fields", new[] { "FieldId", "Name", "Label", "Type", "Required", "MultiValue", "Description" },
            snapshot.Fields.Select(x => new[] { x.FieldId, x.Name, x.Label, x.Type, x.Required.ToString(CultureInfo.InvariantCulture), x.MultiValue.ToString(CultureInfo.InvariantCulture), x.Description })));
        if (includeRaw)
        {
            sheets.Append(Worksheet("Raw", new[] { "Target", "Json" }, new[] { new[] { snapshot.TargetType, snapshot.RawJson } }));
        }
        sheets.Append("</body></html>");
        return sheets.ToString();
    }

    private static string BuildBlankMetadataTemplateXml(TaxonomySnapshot snapshot)
    {
        var headers = snapshot.Fields
            .Select(x => string.IsNullOrWhiteSpace(x.Label) ? x.Name : x.Label)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(x => x, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (headers.Length == 0)
        {
            headers = new[] { "Asset file name" };
        }

        var sheets = new StringBuilder();
        sheets.Append("<html><body>");
        sheets.Append(Worksheet("Metadata Template", headers, Array.Empty<string[]>()));
        sheets.Append(Worksheet("Field Definitions", new[] { "FieldId", "Name", "Label", "Type", "Required", "MultiValue", "Description" },
            snapshot.Fields.Select(x => new[] { x.FieldId, x.Name, x.Label, x.Type, x.Required.ToString(CultureInfo.InvariantCulture), x.MultiValue.ToString(CultureInfo.InvariantCulture), x.Description })));
        sheets.Append("</body></html>");
        return sheets.ToString();
    }

    private static string Worksheet(string name, string[] headers, IEnumerable<string[]> rows)
        => $"<h2>{Xml(name)}</h2><table border=\"1\">{Row(headers)}{string.Concat(rows.Select(Row))}</table>";

    private static string Row(IEnumerable<string> cells)
        => $"<tr>{string.Concat(cells.Select(cell => $"<td>{Xml(cell)}</td>"))}</tr>";

    private static string Xml(string? value) => HtmlEncoder.Default.Encode(value ?? string.Empty);
}

public sealed record BuildTaxonomyArtifactRequest(
    string TargetType,
    string CredentialSetId,
    bool IncludeOptions = true,
    bool IncludeRaw = true,
    string? ProjectId = null,
    string? FileName = null,
    string? Description = null);

public sealed record BuildTaxonomyArtifactResponse(
    ControlPlaneArtifactRecord Artifact,
    string TargetType,
    int FieldCount,
    int OptionCount,
    string FileName);

internal sealed record BynderOAuthCredentials(string BaseUrl, string ClientId, string ClientSecret, string Scopes);
internal sealed record TaxonomySnapshot(string TargetType, List<TaxonomyField> Fields, List<TaxonomyOption> Options, string RawJson);
internal sealed record TaxonomyField(string FieldId, string Name, string Label, string Type, bool Required, bool MultiValue, string Description, string RawJson);
internal sealed record TaxonomyOption(string FieldId, string OptionId, string Name, string Label, bool Active, string RawJson);


