[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string] $ResourceGroup,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string] $AppName,

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $ProjectPath = 'src/Core/Migration.Admin.Api/Migration.Admin.Api.csproj',

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $PublishPath = 'artifacts/publish/admin-api',

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $ZipPath = 'artifacts/publish/admin-api.zip',

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputPath = 'artifacts/p10/site/admin-api-deploy.ps1'
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$scriptRoot = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptRoot)) {
    if (-not [string]::IsNullOrWhiteSpace($PSCommandPath)) {
        $scriptRoot = Split-Path -Parent $PSCommandPath
    }
}
if ([string]::IsNullOrWhiteSpace($scriptRoot)) {
    throw 'Unable to resolve script root.'
}

$repoRoot = Split-Path -Parent (Split-Path -Parent $scriptRoot)

function Resolve-RepoPath {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return [System.IO.Path]::Combine($repoRoot, $Path)
}

$projectFullPath = Resolve-RepoPath -Path $ProjectPath
if (-not (Test-Path -LiteralPath $projectFullPath)) {
    throw ('Admin API project was not found: {0}' -f $projectFullPath)
}

$outputFullPath = Resolve-RepoPath -Path $OutputPath
$outputParent = Split-Path -Parent $outputFullPath
if (-not [string]::IsNullOrWhiteSpace($outputParent) -and -not (Test-Path -LiteralPath $outputParent)) {
    New-Item -ItemType Directory -Path $outputParent -Force | Out-Null
}

$commandText = @"
# Generated by New-P101AdminApiCloudDeployCommands.ps1
# Review before running.

Set-StrictMode -Version 2.0
`$ErrorActionPreference = 'Stop'

`$resourceGroup = '$ResourceGroup'
`$adminApiApp = '$AppName'
`$projectPath = '$ProjectPath'
`$publishPath = '$PublishPath'
`$zipPath = '$ZipPath'

if (Test-Path -LiteralPath `$publishPath) {
    Remove-Item -LiteralPath `$publishPath -Recurse -Force
}

if (Test-Path -LiteralPath `$zipPath) {
    Remove-Item -LiteralPath `$zipPath -Force
}

New-Item -ItemType Directory -Path `$publishPath -Force | Out-Null

dotnet clean `$projectPath

dotnet publish `$projectPath -c Release -o `$publishPath

Push-Location `$publishPath
try {
    tar -a -c -f (Join-Path '..' (Split-Path -Leaf `$zipPath)) *
}
finally {
    Pop-Location
}

az webapp deploy ``
  --resource-group `$resourceGroup ``
  --name `$adminApiApp ``
  --src-path `$zipPath ``
  --type zip ``
  --clean true ``
  --restart true

az webapp restart ``
  --resource-group `$resourceGroup ``
  --name `$adminApiApp
"@

Set-Content -LiteralPath $outputFullPath -Value $commandText -Encoding UTF8
Write-Host ('Admin API cloud deploy commands written to {0}' -f $outputFullPath)
