using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Migration.Connectors.Targets.Aprimo.Workbooks;
using Migration.ControlPlane.Artifacts;
using Migration.ControlPlane.Models;
using Migration.ControlPlane.Services;

namespace Migration.Admin.Api.Endpoints;

public static class TaxonomyBuilderEndpoints
{
    private static readonly HttpClient Http = new();
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web) { WriteIndented = true };

    public static IEndpointRouteBuilder MapTaxonomyBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/taxonomy-builder")
            .WithTags("Taxonomy Builder");

        group.MapPost("/build", async (
            BuildTaxonomyArtifactRequest request,
            ICredentialSetStore credentialStore,
            IArtifactStore artifactStore,
            ILoggerFactory loggerFactory,
            CancellationToken cancellationToken) =>
        {
            if (string.IsNullOrWhiteSpace(request.TargetType))
            {
                return Results.BadRequest(new { error = "targetType is required." });
            }

            if (string.IsNullOrWhiteSpace(request.CredentialSetId))
            {
                return Results.BadRequest(new { error = "credentialSetId is required." });
            }

            var credential = await credentialStore.GetAsync(request.CredentialSetId, cancellationToken).ConfigureAwait(false);
            if (credential is null)
            {
                return Results.NotFound(new { error = $"Credential set '{request.CredentialSetId}' was not found." });
            }

            if (!string.Equals(credential.ConnectorRole, "target", StringComparison.OrdinalIgnoreCase))
            {
                return Results.BadRequest(new { error = "Taxonomy Builder requires a target credential set." });
            }

            var targetKind = NormalizeTargetKind(request.TargetType);
            if (targetKind is null)
            {
                return Results.BadRequest(new { error = "Taxonomy Builder currently supports Bynder, Cloudinary, and Aprimo targets." });
            }

            try
            {
                if (targetKind == "aprimo")
                {
                    return await BuildAprimoConfigurationWorkbookAsync(request, credential, artifactStore, loggerFactory, cancellationToken).ConfigureAwait(false);
                }

                var snapshot = targetKind switch
                {
                    "bynder" => await ReadBynderTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    "cloudinary" => await ReadCloudinaryTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    _ => throw new InvalidOperationException($"Unsupported taxonomy target '{request.TargetType}'.")
                };

                var workbookXml = BuildLegacyWorkbookXml(snapshot, request.IncludeOptions, request.IncludeRaw);
                await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(workbookXml));
                var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName) ? $"{targetKind}-taxonomy-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xls" : request.FileName.Trim());
                if (!fileName.EndsWith(".xls", StringComparison.OrdinalIgnoreCase))
                {
                    fileName += ".xls";
                }

                var artifact = await artifactStore.SaveAsync(
                    stream,
                    fileName,
                    "application/vnd.ms-excel",
                    ArtifactKind.Taxonomy,
                    request.ProjectId,
                    string.IsNullOrWhiteSpace(request.Description) ? $"Generated by Taxonomy Builder from {snapshot.TargetType}" : request.Description,
                    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                    {
                        ["GeneratedBy"] = "TaxonomyBuilder",
                        ["TargetType"] = snapshot.TargetType,
                        ["CredentialSetId"] = credential.CredentialSetId,
                        ["FieldCount"] = snapshot.Fields.Count.ToString(CultureInfo.InvariantCulture),
                        ["OptionCount"] = snapshot.Options.Count.ToString(CultureInfo.InvariantCulture)
                    },
                    cancellationToken).ConfigureAwait(false);

                return Results.Created($"/api/artifacts/{artifact.ArtifactId}", new BuildTaxonomyArtifactResponse(artifact, snapshot.TargetType, snapshot.Fields.Count, snapshot.Options.Count, artifact.FileName));
            }
            catch (Exception ex) when (ex is InvalidOperationException or HttpRequestException or JsonException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }
        })
        .WithSummary("Pull target metadata schema and save it as an Excel taxonomy artifact.");

        return app;
    }

    private static async Task<IResult> BuildAprimoConfigurationWorkbookAsync(
        BuildTaxonomyArtifactRequest request,
        CredentialSetRecord credential,
        IArtifactStore artifactStore,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var subDomain = FirstValue(credential.Values, "subDomain", "aprimoSubDomain", "tenant", "tenantName");
        if (string.IsNullOrWhiteSpace(subDomain))
        {
            var baseUrl = FirstValue(credential.Values, "baseUrl", "url", "tenantUrl", "aprimoBaseUrl");
            subDomain = TryExtractSubDomain(baseUrl);
        }

        var clientId = FirstValue(credential.Values, "clientId", "aprimoClientId", "TargetCredential_ClientId");
        var clientSecret = FirstValue(credential.Values, "clientSecret", "aprimoClientSecret", "secret", "TargetCredential_ClientSecret");

        if (string.IsNullOrWhiteSpace(subDomain))
        {
            throw new InvalidOperationException("Aprimo workbook generation requires a subDomain, aprimoSubDomain, tenant, or Aprimo baseUrl that contains the subdomain.");
        }

        if (string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret))
        {
            throw new InvalidOperationException("Aprimo workbook generation requires clientId and clientSecret credentials.");
        }

        var service = new AprimoConfigurationWorkbookService(new HttpClient(), loggerFactory.CreateLogger<AprimoConfigurationWorkbookService>());
        await using var stream = new MemoryStream();
        var result = await service.GenerateAsync(
            new AprimoConfigurationWorkbookRequest(
                new AprimoConfigurationWorkbookCredentials(subDomain, clientId, clientSecret, FirstValue(credential.Values, "baseUrl", "BaseUrl", "url", "Url", "tenantUrl", "TenantUrl", "aprimoBaseUrl", "AprimoBaseUrl")),
                AprimoConfigurationWorkbookExportOptions.Defaults),
            stream,
            cancellationToken).ConfigureAwait(false);
        stream.Position = 0;

        var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName) ? result.FileName : request.FileName.Trim());
        if (!fileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            fileName = Path.ChangeExtension(fileName, ".xlsx");
        }

        var artifact = await artifactStore.SaveAsync(
            stream,
            fileName,
            result.ContentType,
            ArtifactKind.Taxonomy,
            request.ProjectId,
            string.IsNullOrWhiteSpace(request.Description) ? "Generated by Taxonomy Builder from Aprimo configuration workbook service" : request.Description,
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["GeneratedBy"] = "TaxonomyBuilder",
                ["TargetType"] = "Aprimo",
                ["CredentialSetId"] = credential.CredentialSetId,
                ["WorksheetCount"] = result.WorksheetCount.ToString(CultureInfo.InvariantCulture),
                ["WorkbookKind"] = "AprimoConfigurationWorkbook"
            },
            cancellationToken).ConfigureAwait(false);

        var fieldCount = result.RowCounts.TryGetValue("Field definitions", out var fields) ? fields : 0;
        return Results.Created($"/api/artifacts/{artifact.ArtifactId}", new BuildTaxonomyArtifactResponse(artifact, "Aprimo", fieldCount, 0, artifact.FileName));
    }

    private static async Task<TaxonomySnapshot> ReadBynderTaxonomyAsync(CredentialSetRecord credential, BuildTaxonomyArtifactRequest request, CancellationToken cancellationToken)
    {
        var baseUrl = FirstValue(credential.Values, "baseUrl", "url", "domain", "bynderDomain");
        var token = FirstValue(credential.Values, "accessToken", "apiToken", "token", "bearerToken");
        if (string.IsNullOrWhiteSpace(baseUrl) || string.IsNullOrWhiteSpace(token)) throw new InvalidOperationException("Bynder credentials require baseUrl and accessToken/apiToken.");
        using var httpRequest = new HttpRequestMessage(HttpMethod.Get, CombineUrl(baseUrl, "/api/v4/metaproperties/"));
        httpRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
        using var response = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
        var json = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode) throw new HttpRequestException($"Bynder metaproperties request failed: {(int)response.StatusCode} {response.ReasonPhrase}. {json}");
        var root = JsonNode.Parse(json) ?? new JsonArray();
        var fields = new List<TaxonomyField>();
        var options = new List<TaxonomyOption>();
        foreach (var item in AsArray(root).OfType<JsonObject>())
        {
            var id = Text(item, "id", "uuid", "name", "propertyId");
            fields.Add(new TaxonomyField(id, Text(item, "name", "propertyName", "technicalName", "id"), Text(item, "label", "displayName", "name", "propertyName"), Text(item, "type", "inputType", "fieldType"), Bool(item, "required", "isRequired", "mandatory"), Bool(item, "isMultiselect", "multiSelect", "multiselect", "multiple"), Text(item, "description", "helpText"), item.ToJsonString(JsonOptions)));
        }
        return new TaxonomySnapshot("Bynder", fields, options, json);
    }

    private static async Task<TaxonomySnapshot> ReadCloudinaryTaxonomyAsync(CredentialSetRecord credential, BuildTaxonomyArtifactRequest request, CancellationToken cancellationToken)
    {
        var cloudName = FirstValue(credential.Values, "cloudName", "cloud_name");
        var apiKey = FirstValue(credential.Values, "apiKey", "api_key");
        var apiSecret = FirstValue(credential.Values, "apiSecret", "api_secret", "secret");
        if (string.IsNullOrWhiteSpace(cloudName) || string.IsNullOrWhiteSpace(apiKey) || string.IsNullOrWhiteSpace(apiSecret)) throw new InvalidOperationException("Cloudinary credentials require cloudName, apiKey, and apiSecret.");
        using var httpRequest = new HttpRequestMessage(HttpMethod.Get, $"https://api.cloudinary.com/v1_1/{Uri.EscapeDataString(cloudName)}/metadata_fields");
        httpRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(Encoding.ASCII.GetBytes($"{apiKey}:{apiSecret}")));
        using var response = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
        var json = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode) throw new HttpRequestException($"Cloudinary metadata fields request failed: {(int)response.StatusCode} {response.ReasonPhrase}. {json}");
        var root = JsonNode.Parse(json) ?? new JsonObject();
        var fieldNodes = root is JsonObject rootObj && rootObj["metadata_fields"] is JsonArray arr ? arr : AsArray(root);
        var fields = fieldNodes.OfType<JsonObject>().Select(obj => new TaxonomyField(Text(obj, "external_id", "id", "name"), Text(obj, "external_id", "name", "id"), Text(obj, "label", "display_name", "external_id", "name"), Text(obj, "type"), Bool(obj, "mandatory", "required"), Bool(obj, "multiple", "multiValue"), Text(obj, "description", "help_text"), obj.ToJsonString(JsonOptions))).ToList();
        return new TaxonomySnapshot("Cloudinary", fields, new List<TaxonomyOption>(), json);
    }

    private static JsonArray AsArray(JsonNode node) => node as JsonArray ?? new JsonArray(node);
    private static string Text(JsonObject obj, params string[] keys) { foreach (var key in keys) if (obj[key] is JsonValue value && !string.IsNullOrWhiteSpace(value.ToString())) return value.ToString(); return string.Empty; }
    private static bool Bool(JsonObject obj, params string[] keys) { foreach (var key in keys) if (obj[key] is JsonValue value && bool.TryParse(value.ToString(), out var parsed)) return parsed; return false; }
    private static string FirstValue(IReadOnlyDictionary<string, string> values, params string[] keys)
    {
        foreach (var key in keys)
        {
            foreach (var pair in values)
            {
                if (pair.Key.Equals(key, StringComparison.OrdinalIgnoreCase)
                    && !string.IsNullOrWhiteSpace(pair.Value)
                    && pair.Value != "********")
                {
                    return pair.Value.Trim();
                }
            }
        }

        return string.Empty;
    }
    private static string? NormalizeTargetKind(string targetType) { var value = targetType.Trim().ToLowerInvariant(); if (value.Contains("bynder")) return "bynder"; if (value.Contains("cloudinary")) return "cloudinary"; if (value.Contains("aprimo")) return "aprimo"; return null; }
    private static string CombineUrl(string baseUrl, string path) => baseUrl.TrimEnd('/') + "/" + path.TrimStart('/');
    private static string? TryExtractSubDomain(string url)
    {
        if (string.IsNullOrWhiteSpace(url)) return null;
        var value = url.Trim();
        if (!value.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
            && !value.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            value = "https://" + value;
        }

        var host = Uri.TryCreate(value, UriKind.Absolute, out var uri)
            ? uri.Host
            : url.Trim().Split('/')[0];

        if (host.StartsWith("www.", StringComparison.OrdinalIgnoreCase)) host = host[4..];
        if (host.EndsWith(".dam.aprimo.com", StringComparison.OrdinalIgnoreCase)) return host[..^".dam.aprimo.com".Length];
        if (host.EndsWith(".aprimo.com", StringComparison.OrdinalIgnoreCase)) return host[..^".aprimo.com".Length];
        return host.Split('.')[0];
    }
    private static string MakeSafeFileName(string value) { var invalid = Path.GetInvalidFileNameChars(); var safe = new string(value.Select(ch => invalid.Contains(ch) ? '_' : ch).ToArray()); return string.IsNullOrWhiteSpace(safe) ? $"taxonomy-{Guid.NewGuid():N}.xlsx" : safe; }

    private static string BuildLegacyWorkbookXml(TaxonomySnapshot snapshot, bool includeOptions, bool includeRaw)
    {
        var sheets = new StringBuilder();
        sheets.Append(Worksheet("Fields", new[] { "FieldId", "Name", "Label", "Type", "Required", "MultiValue", "Description" }, snapshot.Fields.Select(x => new[] { x.FieldId, x.Name, x.Label, x.Type, x.Required.ToString(), x.MultiValue.ToString(), x.Description })));
        if (includeRaw) sheets.Append(Worksheet("Raw", new[] { "Target", "Json" }, new[] { new[] { snapshot.TargetType, snapshot.RawJson } }));
        return $"<?xml version=\"1.0\"?><Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\">{sheets}</Workbook>";
    }
    private static string Worksheet(string name, string[] headers, IEnumerable<string[]> rows) => $"<Worksheet ss:Name=\"{Xml(name)}\"><Table>{Row(headers)}{string.Concat(rows.Select(Row))}</Table></Worksheet>";
    private static string Row(IEnumerable<string> cells) => $"<Row>{string.Concat(cells.Select(cell => $"<Cell><Data ss:Type=\"String\">{Xml(cell)}</Data></Cell>"))}</Row>";
    private static string Xml(string? value) => HtmlEncoder.Default.Encode(value ?? string.Empty);
}

public sealed record BuildTaxonomyArtifactRequest(string TargetType, string CredentialSetId, bool IncludeOptions = true, bool IncludeRaw = true, string? ProjectId = null, string? FileName = null, string? Description = null);
public sealed record BuildTaxonomyArtifactResponse(ControlPlaneArtifactRecord Artifact, string TargetType, int FieldCount, int OptionCount, string FileName);
internal sealed record TaxonomySnapshot(string TargetType, List<TaxonomyField> Fields, List<TaxonomyOption> Options, string RawJson);
internal sealed record TaxonomyField(string FieldId, string Name, string Label, string Type, bool Required, bool MultiValue, string Description, string RawJson);
internal sealed record TaxonomyOption(string FieldId, string OptionId, string Name, string Label, bool Active, string RawJson);
