param(
    [switch]$Apply,
    [switch]$WriteCommandFile
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Push-Location $repoRoot

try {
    $targets = @()

    if (Test-Path ".\tools\dropins") {
        $dropinDirs = Get-ChildItem ".\tools\dropins" -Directory -ErrorAction SilentlyContinue |
            Where-Object {
                $_.Name -like "p2-set*" -or
                $_.Name -like "post-p2-cleanup-set001*" -or
                $_.Name -like "post-p2-cleanup-set002*"
            }

        foreach ($dir in $dropinDirs) {
            $targets += $dir.FullName.Substring($repoRoot.Path.Length + 1)
        }

        $dropinFiles = Get-ChildItem ".\tools\dropins" -File -ErrorAction SilentlyContinue |
            Where-Object {
                $_.Name -like "apply-p2-set*.ps1" -or
                $_.Name -like "apply-post-p2-cleanup-set001*.ps1" -or
                $_.Name -like "*fix*.ps1" -or
                $_.Name -like "*corrective*.ps1"
            }

        foreach ($file in $dropinFiles) {
            $targets += $file.FullName.Substring($repoRoot.Path.Length + 1)
        }
    }

    $targets = @($targets) | Sort-Object -Unique

    Write-Host "Post-P2 Drop-in Artifact Cleanup"
    Write-Host "Repo root: $repoRoot"
    Write-Host "Apply removals: $Apply"
    Write-Host "Write command file: $WriteCommandFile"
    Write-Host ""
    Write-Host "Candidate targets: $($targets.Count)"
    Write-Host ""

    foreach ($target in $targets) {
        Write-Host "  $target"
    }

    $reportDir = ".\docs\post-p2-cleanup"
    if (!(Test-Path $reportDir)) {
        New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
    }

    $reportPath = Join-Path $reportDir "P2_DROPIN_ARTIFACT_CLEANUP_REPORT.md"
    $report = @()
    $report += "# P2 Drop-in Artifact Cleanup Report"
    $report += ""
    $report += "Generated: $(Get-Date -Format o)"
    $report += ""
    $report += "## Candidate targets"
    if ($targets.Count -eq 0) {
        $report += "- None"
    }
    else {
        foreach ($target in $targets) {
            $report += "- $target"
        }
    }

    $report += ""
    $report += "## Notes"
    $report += ""
    $report += "- This report only targets applied drop-in artifacts."
    $report += "- It does not target source code, tests, validators, or docs."
    $report += "- Run full P2 validation after applying cleanup."

    Set-Content -Path $reportPath -Value $report -Encoding UTF8

    if ($WriteCommandFile) {
        $cmdPath = Join-Path $reportDir "remove-p2-dropin-artifacts.git-rm.ps1"
        $cmd = @()
        $cmd += '$ErrorActionPreference = "Stop"'
        $cmd += '# Generated by remove-post-p2-dropin-artifacts.ps1'
        $cmd += '# Review before running.'
        $cmd += ""

        foreach ($target in $targets) {
            $normalized = $target -replace "\\", "/"
            $cmd += "git rm -r -- '$normalized'"
        }

        Set-Content -Path $cmdPath -Value $cmd -Encoding UTF8
        Write-Host ""
        Write-Host "Command file written: $cmdPath"
    }

    if ($Apply) {
        foreach ($target in $targets) {
            if (Test-Path $target) {
                Write-Host "Removing $target"
                git rm -r -- $target
            }
        }
    }
    else {
        Write-Host ""
        Write-Host "Preview only. Re-run with -Apply to remove, or -WriteCommandFile to generate commands."
    }

    Write-Host ""
    Write-Host "Report written: $reportPath"
}
finally {
    Pop-Location
}
