using Migration.ControlPlane.Artifacts;
using Migration.ControlPlane.ManifestBuilder;

namespace Migration.Admin.Api.Endpoints;

public static class ManifestBuilderEndpoints
{
    public static IEndpointRouteBuilder MapManifestBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/manifest-builder")
            .WithTags("Manifest Builder");

        group.MapGet("/sources", (ManifestBuilderServiceRegistry registry) =>
        {
            return Results.Ok(registry.GetSources());
        })
        .WithName("GetManifestBuilderSources")
        .WithSummary("Lists source connectors and services that can generate manifest artifacts.");

        group.MapPost("/build", async (
            BuildSourceManifestRequest request,
            ManifestBuilderServiceRegistry registry,
            IArtifactStore artifacts,
            CancellationToken cancellationToken) =>
        {
            if (string.IsNullOrWhiteSpace(request.SourceType))
            {
                return Results.BadRequest(new { error = "SourceType is required." });
            }

            if (string.IsNullOrWhiteSpace(request.ServiceName))
            {
                return Results.BadRequest(new { error = "ServiceName is required." });
            }

            var service = registry.TryGetService(request.SourceType, request.ServiceName);

            if (service is null)
            {
                return Results.BadRequest(new
                {
                    error = $"No manifest builder service is registered for source '{request.SourceType}' and service '{request.ServiceName}'."
                });
            }

            BuildSourceManifestResult result;

            try
            {
                result = await service.BuildAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }

            //await using var stream = new MemoryStream(result.ContentBytes);

            await using var stream = result.ContentBytes is not null
                ? new MemoryStream(result.ContentBytes)
                : new MemoryStream(System.Text.Encoding.UTF8.GetBytes(result.Content ?? ""));

            var artifact = await artifacts.SaveAsync(
                stream,
                result.FileName,
                string.IsNullOrWhiteSpace(result.ContentType) ? "application/octet-stream" : result.ContentType,
                ArtifactKind.Manifest,
                projectId: null,
                description: $"Generated by Manifest Builder from {result.SourceType}/{result.ServiceName}",
                cancellationToken: cancellationToken).ConfigureAwait(false);

            return Results.Created(
                $"/api/artifacts/{artifact.ArtifactId}",
                new BuildSourceManifestResponse(
                    artifact.ArtifactId,
                    artifact.ArtifactId,
                    result.SourceType,
                    result.ServiceName,
                    artifact.FileName,
                    artifact.ContentType,
                    result.RowCount,
                    $"/api/artifacts/{Uri.EscapeDataString(artifact.ArtifactId)}/download",
                    artifact.CreatedUtc));
        })
        .WithName("BuildSourceManifest")
        .WithSummary("Runs a source manifest service and saves the generated file as a Manifest artifact.");

        return app;
    }
}