using Migration.ControlPlane.ManifestBuilder;

namespace Migration.Admin.Api.Endpoints;

public static class ManifestBuilderEndpoints
{
    public static IEndpointRouteBuilder MapManifestBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/manifest-builder")
            .WithTags("Manifest Builder");

        group.MapGet("/sources", (ManifestBuilderServiceRegistry registry) =>
        {
            return Results.Ok(registry.GetSources());
        })
        .WithName("GetManifestBuilderSources")
        .WithSummary("Lists source connectors and services that can generate downloadable manifests.");

        group.MapPost("/build", async (
            BuildSourceManifestRequest request,
            ManifestBuilderServiceRegistry registry,
            ManifestBuilderFileStore files,
            CancellationToken cancellationToken) =>
        {
            if (string.IsNullOrWhiteSpace(request.SourceType))
            {
                return Results.BadRequest(new { error = "SourceType is required." });
            }

            if (string.IsNullOrWhiteSpace(request.ServiceName))
            {
                return Results.BadRequest(new { error = "ServiceName is required." });
            }

            var service = registry.TryGetService(request.SourceType, request.ServiceName);

            if (service is null)
            {
                return Results.BadRequest(new
                {
                    error = $"No manifest builder service is registered for source '{request.SourceType}' and service '{request.ServiceName}'."
                });
            }

            BuildSourceManifestResult result;

            try
            {
                result = await service.BuildAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }

            var stored = await files.SaveAsync(result, cancellationToken).ConfigureAwait(false);

            return Results.Ok(new BuildSourceManifestResponse(
                stored.ManifestId,
                stored.SourceType,
                stored.ServiceName,
                stored.FileName,
                stored.ContentType,
                stored.RowCount,
                $"/api/manifest-builder/results/{Uri.EscapeDataString(stored.ManifestId)}/download",
                stored.CreatedUtc));
        })
        .WithName("BuildSourceManifest")
        .WithSummary("Runs a source manifest service and stores a downloadable manifest file.");

        group.MapGet("/results/{manifestId}/download", (
            string manifestId,
            ManifestBuilderFileStore files) =>
        {
            var stored = files.TryGet(manifestId);

            if (stored is null || !File.Exists(stored.Path))
            {
                return Results.NotFound(new { error = $"Manifest '{manifestId}' was not found." });
            }

            return Results.File(
                stored.Path,
                stored.ContentType,
                stored.FileName);
        })
        .WithName("DownloadBuiltManifest")
        .WithSummary("Downloads a manifest generated by Manifest Builder.");

        return app;
    }
}
