using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Migration.ControlPlane.Artifacts;

namespace Migration.Admin.Api.Endpoints;

public static class MappingBuilderEndpoints
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    public static IEndpointRouteBuilder MapMappingBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/mapping-builder")
            .WithTags("Mapping Builder");

        group.MapGet("/manifests/{artifactId}/columns", async (
                string artifactId,
                IArtifactStore artifacts,
                CancellationToken cancellationToken) =>
            {
                var preview = await artifacts.PreviewManifestAsync(artifactId, take: 10, cancellationToken).ConfigureAwait(false);
                return Results.Ok(new
                {
                    preview.ArtifactId,
                    preview.FileName,
                    preview.Columns,
                    preview.SampleRows
                });
            })
            .WithSummary("Read manifest columns and sample rows for the mapping builder.");

        group.MapPost("/mappings", async (
                SaveMappingArtifactRequest request,
                IArtifactStore artifacts,
                CancellationToken cancellationToken) =>
            {
                if (string.IsNullOrWhiteSpace(request.ProfileName))
                {
                    return Results.BadRequest(new { error = "profileName is required." });
                }

                if (string.IsNullOrWhiteSpace(request.SourceType))
                {
                    return Results.BadRequest(new { error = "sourceType is required." });
                }

                if (string.IsNullOrWhiteSpace(request.TargetType))
                {
                    return Results.BadRequest(new { error = "targetType is required." });
                }

                var cleanedMappings = request.FieldMappings
                    .Where(x => !string.IsNullOrWhiteSpace(x.Source) && !string.IsNullOrWhiteSpace(x.Target))
                    .Select(x => new MappingBuilderFieldMap(
                        x.Source.Trim(),
                        x.Target.Trim(),
                        string.IsNullOrWhiteSpace(x.Transform) ? null : x.Transform.Trim()))
                    .ToList();

                if (cleanedMappings.Count == 0)
                {
                    return Results.BadRequest(new { error = "At least one field mapping with source and target is required." });
                }

                var requiredTargetFields = request.RequiredTargetFields
                    .Where(x => !string.IsNullOrWhiteSpace(x))
                    .Select(x => x.Trim())
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();

                var mappingProfile = new MappingProfileDocument(
                    request.ProfileName.Trim(),
                    request.SourceType.Trim(),
                    request.TargetType.Trim(),
                    cleanedMappings,
                    requiredTargetFields);

                var json = JsonSerializer.Serialize(mappingProfile, JsonOptions);
                await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(json));

                var fileName = string.IsNullOrWhiteSpace(request.FileName)
                    ? MakeSafeFileName($"{request.ProfileName.Trim()}.mapping.json")
                    : MakeSafeFileName(request.FileName.Trim());

                if (!fileName.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
                {
                    fileName += ".json";
                }

                var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    ["GeneratedBy"] = "MappingBuilder",
                    ["SourceType"] = mappingProfile.SourceType,
                    ["TargetType"] = mappingProfile.TargetType,
                    ["FieldMappingCount"] = cleanedMappings.Count.ToString(System.Globalization.CultureInfo.InvariantCulture)
                };

                if (!string.IsNullOrWhiteSpace(request.ManifestArtifactId))
                {
                    metadata["ManifestArtifactId"] = request.ManifestArtifactId.Trim();
                }

                var artifact = await artifacts.SaveAsync(
                    stream,
                    fileName,
                    "application/json",
                    ArtifactKind.Mapping,
                    request.ProjectId,
                    string.IsNullOrWhiteSpace(request.Description) ? "Generated by Mapping Builder" : request.Description,
                    metadata,
                    cancellationToken).ConfigureAwait(false);

                return Results.Created($"/api/artifacts/{artifact.ArtifactId}", new
                {
                    artifact,
                    mappingProfile
                });
            })
            .WithSummary("Save a mapping profile as a mapping artifact.");

        return app;
    }

    private static string MakeSafeFileName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var safe = new string(value.Select(ch => invalid.Contains(ch) ? '_' : ch).ToArray());
        return string.IsNullOrWhiteSpace(safe) ? $"mapping-{Guid.NewGuid():N}.json" : safe;
    }
}

public sealed record SaveMappingArtifactRequest(
    string ProfileName,
    string SourceType,
    string TargetType,
    List<MappingBuilderFieldMap> FieldMappings,
    List<string> RequiredTargetFields,
    string? ManifestArtifactId = null,
    string? ProjectId = null,
    string? FileName = null,
    string? Description = null);

public sealed record MappingBuilderFieldMap(
    string Source,
    string Target,
    string? Transform = null);

public sealed record MappingProfileDocument(
    [property: JsonPropertyName("profileName")] string ProfileName,
    [property: JsonPropertyName("sourceType")] string SourceType,
    [property: JsonPropertyName("targetType")] string TargetType,
    [property: JsonPropertyName("fieldMappings")] List<MappingBuilderFieldMap> FieldMappings,
    [property: JsonPropertyName("requiredTargetFields")] List<string> RequiredTargetFields);
