using System.Globalization;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Migration.ControlPlane.Artifacts;
using Migration.ControlPlane.Models;
using Migration.ControlPlane.Services;

namespace Migration.Admin.Api.Endpoints;

public static class TaxonomyBuilderEndpoints
{
    private static readonly HttpClient Http = new();
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true
    };

    public static IEndpointRouteBuilder MapTaxonomyBuilderEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/taxonomy-builder")
            .WithTags("Taxonomy Builder");

        group.MapPost("/build", async (
            BuildTaxonomyArtifactRequest request,
            ICredentialSetStore credentialStore,
            IArtifactStore artifactStore,
            CancellationToken cancellationToken) =>
        {
            if (string.IsNullOrWhiteSpace(request.TargetType))
            {
                return Results.BadRequest(new { error = "targetType is required." });
            }

            if (string.IsNullOrWhiteSpace(request.CredentialSetId))
            {
                return Results.BadRequest(new { error = "credentialSetId is required." });
            }

            var credential = await credentialStore.GetAsync(request.CredentialSetId, cancellationToken).ConfigureAwait(false);
            if (credential is null)
            {
                return Results.NotFound(new { error = $"Credential set '{request.CredentialSetId}' was not found." });
            }

            if (!string.Equals(credential.ConnectorRole, "target", StringComparison.OrdinalIgnoreCase))
            {
                return Results.BadRequest(new { error = "Taxonomy Builder requires a target credential set." });
            }

            var targetKind = NormalizeTargetKind(request.TargetType);
            if (targetKind is null)
            {
                return Results.BadRequest(new { error = "Taxonomy Builder currently supports Bynder, Cloudinary, and Aprimo targets." });
            }

            TaxonomySnapshot snapshot;
            try
            {
                snapshot = targetKind switch
                {
                    "bynder" => await ReadBynderTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    "cloudinary" => await ReadCloudinaryTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    "aprimo" => await ReadAprimoTaxonomyAsync(credential, request, cancellationToken).ConfigureAwait(false),
                    _ => throw new InvalidOperationException($"Unsupported taxonomy target '{request.TargetType}'.")
                };
            }
            catch (Exception ex) when (ex is InvalidOperationException or HttpRequestException or JsonException)
            {
                return Results.BadRequest(new { error = ex.Message });
            }

            var workbookXml = BuildWorkbook(snapshot, request.IncludeOptions, request.IncludeRaw);
            await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(workbookXml));

            var fileName = MakeSafeFileName(string.IsNullOrWhiteSpace(request.FileName)
                ? $"{targetKind}-taxonomy-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.xls"
                : request.FileName.Trim());

            if (!fileName.EndsWith(".xls", StringComparison.OrdinalIgnoreCase))
            {
                fileName += ".xls";
            }

            var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["GeneratedBy"] = "TaxonomyBuilder",
                ["TargetType"] = snapshot.TargetType,
                ["CredentialSetId"] = credential.CredentialSetId,
                ["FieldCount"] = snapshot.Fields.Count.ToString(CultureInfo.InvariantCulture),
                ["OptionCount"] = snapshot.Options.Count.ToString(CultureInfo.InvariantCulture)
            };

            var artifact = await artifactStore.SaveAsync(
                stream,
                fileName,
                "application/vnd.ms-excel",
                ArtifactKind.Taxonomy,
                request.ProjectId,
                string.IsNullOrWhiteSpace(request.Description)
                    ? $"Generated by Taxonomy Builder from {snapshot.TargetType}"
                    : request.Description,
                metadata,
                cancellationToken).ConfigureAwait(false);

            return Results.Created($"/api/artifacts/{artifact.ArtifactId}", new BuildTaxonomyArtifactResponse(
                artifact,
                snapshot.TargetType,
                snapshot.Fields.Count,
                snapshot.Options.Count,
                artifact.FileName));
        })
        .WithSummary("Pull target metadata schema and save it as an Excel taxonomy artifact.");

        return app;
    }

    private static async Task<TaxonomySnapshot> ReadBynderTaxonomyAsync(
        CredentialSetRecord credential,
        BuildTaxonomyArtifactRequest request,
        CancellationToken cancellationToken)
    {
        var baseUrl = FirstValue(credential.Values, "baseUrl", "url", "domain", "bynderDomain");
        var token = FirstValue(credential.Values, "accessToken", "apiToken", "token", "bearerToken");

        if (string.IsNullOrWhiteSpace(baseUrl))
        {
            throw new InvalidOperationException("Bynder credentials require baseUrl, url, domain, or bynderDomain.");
        }

        if (string.IsNullOrWhiteSpace(token))
        {
            throw new InvalidOperationException("Bynder credentials require accessToken, apiToken, token, or bearerToken.");
        }

        var uri = CombineUrl(baseUrl, "/api/v4/metaproperties/");
        using var httpRequest = new HttpRequestMessage(HttpMethod.Get, uri);
        httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        using var response = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
        var json = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException($"Bynder metaproperties request failed: {(int)response.StatusCode} {response.ReasonPhrase}. {json}");
        }

        var root = JsonNode.Parse(json) ?? new JsonArray();
        var fields = new List<TaxonomyField>();
        var options = new List<TaxonomyOption>();

        foreach (var item in AsArray(root))
        {
            if (item is not JsonObject obj)
            {
                continue;
            }

            var id = Text(obj, "id", "uuid", "name", "propertyId");
            var name = Text(obj, "name", "propertyName", "technicalName", "id");
            var label = Text(obj, "label", "displayName", "name", "propertyName");
            var type = Text(obj, "type", "inputType", "fieldType");

            fields.Add(new TaxonomyField(
                id,
                name,
                label,
                type,
                Bool(obj, "required", "isRequired", "mandatory"),
                Bool(obj, "isMultiselect", "multiSelect", "multiselect", "multiple"),
                Text(obj, "description", "helpText"),
                JsonSerializer.Serialize(obj, JsonOptions)));

            if (request.IncludeOptions)
            {
                foreach (var option in ExtractOptionObjects(obj, "options", "values", "propertyOptions"))
                {
                    options.Add(new TaxonomyOption(
                        id,
                        Text(option, "id", "uuid", "name"),
                        Text(option, "name", "label", "value"),
                        Text(option, "label", "name", "value"),
                        Bool(option, new[] { "active", "isActive", "enabled" }, defaultValue: true),
                        JsonSerializer.Serialize(option, JsonOptions)));
                }
            }
        }

        return new TaxonomySnapshot("Bynder", fields, options, json);
    }

    private static async Task<TaxonomySnapshot> ReadCloudinaryTaxonomyAsync(
        CredentialSetRecord credential,
        BuildTaxonomyArtifactRequest request,
        CancellationToken cancellationToken)
    {
        var cloudName = FirstValue(credential.Values, "cloudName", "cloud_name");
        var apiKey = FirstValue(credential.Values, "apiKey", "api_key");
        var apiSecret = FirstValue(credential.Values, "apiSecret", "api_secret", "secret");

        if (string.IsNullOrWhiteSpace(cloudName) || string.IsNullOrWhiteSpace(apiKey) || string.IsNullOrWhiteSpace(apiSecret))
        {
            throw new InvalidOperationException("Cloudinary credentials require cloudName, apiKey, and apiSecret.");
        }

        using var httpRequest = new HttpRequestMessage(HttpMethod.Get, $"https://api.cloudinary.com/v1_1/{Uri.EscapeDataString(cloudName)}/metadata_fields");
        httpRequest.Headers.Authorization = new AuthenticationHeaderValue(
            "Basic",
            Convert.ToBase64String(Encoding.ASCII.GetBytes($"{apiKey}:{apiSecret}")));
        httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        using var response = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
        var json = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException($"Cloudinary metadata fields request failed: {(int)response.StatusCode} {response.ReasonPhrase}. {json}");
        }

        var root = JsonNode.Parse(json) ?? new JsonObject();
        var fieldNodes = root is JsonObject rootObj && rootObj["metadata_fields"] is JsonArray arr
            ? arr
            : AsArray(root);

        var fields = new List<TaxonomyField>();
        var options = new List<TaxonomyOption>();

        foreach (var item in fieldNodes)
        {
            if (item is not JsonObject obj)
            {
                continue;
            }

            var id = Text(obj, "external_id", "id", "name");
            fields.Add(new TaxonomyField(
                id,
                Text(obj, "external_id", "name", "id"),
                Text(obj, "label", "display_name", "external_id", "name"),
                Text(obj, "type"),
                Bool(obj, "mandatory", "required"),
                IsMultiValueCloudinaryField(obj),
                Text(obj, "description", "help_text"),
                JsonSerializer.Serialize(obj, JsonOptions)));

            if (request.IncludeOptions)
            {
                foreach (var option in ExtractOptionObjects(obj, "datasource", "values", "options"))
                {
                    options.Add(new TaxonomyOption(
                        id,
                        Text(option, "external_id", "id", "value"),
                        Text(option, "value", "label", "name"),
                        Text(option, "label", "value", "name"),
                        Bool(option, new[] { "active", "enabled" }, defaultValue: true),
                        JsonSerializer.Serialize(option, JsonOptions)));
                }
            }
        }

        return new TaxonomySnapshot("Cloudinary", fields, options, json);
    }

    private static async Task<TaxonomySnapshot> ReadAprimoTaxonomyAsync(
        CredentialSetRecord credential,
        BuildTaxonomyArtifactRequest request,
        CancellationToken cancellationToken)
    {
        var baseUrl = FirstValue(credential.Values, "baseUrl", "url", "tenantUrl", "aprimoBaseUrl");
        var token = FirstValue(credential.Values, "accessToken", "token", "bearerToken");

        if (string.IsNullOrWhiteSpace(baseUrl))
        {
            throw new InvalidOperationException("Aprimo credentials require baseUrl, url, tenantUrl, or aprimoBaseUrl.");
        }

        if (string.IsNullOrWhiteSpace(token))
        {
            throw new InvalidOperationException("Aprimo credentials require accessToken, token, or bearerToken.");
        }

        var endpoints = new[]
        {
            "/api/core/metadatafields?limit=1000",
            "/api/core/metadata-fields?limit=1000",
            "/api/metadatafields?limit=1000"
        };

        string? json = null;
        HttpResponseMessage? lastResponse = null;

        foreach (var endpoint in endpoints)
        {
            using var httpRequest = new HttpRequestMessage(HttpMethod.Get, CombineUrl(baseUrl, endpoint));
            httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            httpRequest.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            lastResponse = await Http.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
            json = await lastResponse.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            if (lastResponse.IsSuccessStatusCode)
            {
                break;
            }
        }

        if (lastResponse is null || !lastResponse.IsSuccessStatusCode || json is null)
        {
            throw new HttpRequestException($"Aprimo metadata fields request failed: {(int?)lastResponse?.StatusCode} {lastResponse?.ReasonPhrase}. {json}");
        }

        var root = JsonNode.Parse(json) ?? new JsonObject();
        var fieldNodes = FindFirstArray(root, "items", "fields", "metadataFields", "data") ?? AsArray(root);
        var fields = new List<TaxonomyField>();
        var options = new List<TaxonomyOption>();

        foreach (var item in fieldNodes)
        {
            if (item is not JsonObject obj)
            {
                continue;
            }

            var id = Text(obj, "id", "fieldName", "name");
            fields.Add(new TaxonomyField(
                id,
                Text(obj, "fieldName", "name", "id"),
                Text(obj, "label", "localizedLabel", "displayName", "name", "fieldName"),
                Text(obj, "dataType", "type", "fieldType"),
                Bool(obj, "required", "isRequired", "mandatory"),
                Bool(obj, "multiValue", "isMultiValue", "allowMultipleValues", "multiple"),
                Text(obj, "description", "helpText"),
                JsonSerializer.Serialize(obj, JsonOptions)));

            if (request.IncludeOptions)
            {
                foreach (var option in ExtractOptionObjects(obj, "options", "values", "listValues", "allowedValues"))
                {
                    options.Add(new TaxonomyOption(
                        id,
                        Text(option, "id", "value", "name"),
                        Text(option, "value", "name", "label"),
                        Text(option, "label", "name", "value"),
                        Bool(option, new[] { "active", "isActive", "enabled" }, defaultValue: true),
                        JsonSerializer.Serialize(option, JsonOptions)));
                }
            }
        }

        return new TaxonomySnapshot("Aprimo", fields, options, json);
    }

    private static JsonArray AsArray(JsonNode node)
    {
        return node as JsonArray ?? new JsonArray(node);
    }

    private static JsonArray? FindFirstArray(JsonNode node, params string[] keys)
    {
        if (node is not JsonObject obj)
        {
            return node as JsonArray;
        }

        foreach (var key in keys)
        {
            if (obj[key] is JsonArray arr)
            {
                return arr;
            }
        }

        return null;
    }

    private static IEnumerable<JsonObject> ExtractOptionObjects(JsonObject field, params string[] keys)
    {
        foreach (var key in keys)
        {
            var node = field[key];
            if (node is JsonArray arr)
            {
                foreach (var item in arr.OfType<JsonObject>())
                {
                    yield return item;
                }
            }
            else if (node is JsonObject obj)
            {
                foreach (var nestedKey in new[] { "values", "options", "items", "datasource" })
                {
                    if (obj[nestedKey] is JsonArray nested)
                    {
                        foreach (var item in nested.OfType<JsonObject>())
                        {
                            yield return item;
                        }
                    }
                }
            }
        }
    }

    private static string Text(JsonObject obj, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (obj[key] is JsonValue value)
            {
                var text = value.ToString();
                if (!string.IsNullOrWhiteSpace(text))
                {
                    return text;
                }
            }
        }

        return string.Empty;
    }

    private static bool Bool(JsonObject obj, params string[] keys)
    {
        return Bool(obj, keys, defaultValue: false);
    }

    private static bool Bool(JsonObject obj, string[] keys, bool defaultValue)
    {
        foreach (var key in keys)
        {
            if (obj[key] is JsonValue value)
            {
                if (value.TryGetValue<bool>(out var boolValue))
                {
                    return boolValue;
                }

                if (bool.TryParse(value.ToString(), out var parsed))
                {
                    return parsed;
                }
            }
        }

        return defaultValue;
    }

    private static bool IsMultiValueCloudinaryField(JsonObject obj)
    {
        var type = Text(obj, "type");
        return type.Contains("multi", StringComparison.OrdinalIgnoreCase) || Bool(obj, "multiple", "multiValue");
    }

    private static string FirstValue(IReadOnlyDictionary<string, string> values, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (values.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value) && value != "********")
            {
                return value.Trim();
            }
        }

        return string.Empty;
    }

    private static string? NormalizeTargetKind(string targetType)
    {
        var value = targetType.Trim().ToLowerInvariant();
        if (value.Contains("bynder")) return "bynder";
        if (value.Contains("cloudinary")) return "cloudinary";
        if (value.Contains("aprimo")) return "aprimo";
        return null;
    }

    private static string CombineUrl(string baseUrl, string path)
    {
        return baseUrl.TrimEnd('/') + "/" + path.TrimStart('/');
    }

    private static string MakeSafeFileName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var safe = new string(value.Select(ch => invalid.Contains(ch) ? '_' : ch).ToArray());
        return string.IsNullOrWhiteSpace(safe) ? $"taxonomy-{Guid.NewGuid():N}.xls" : safe;
    }

    private static string BuildWorkbook(TaxonomySnapshot snapshot, bool includeOptions, bool includeRaw)
    {
        var sheets = new StringBuilder();
        sheets.Append(Worksheet("Fields", new[] { "FieldId", "Name", "Label", "Type", "Required", "MultiValue", "Description" },
            snapshot.Fields.Select(x => new[] { x.FieldId, x.Name, x.Label, x.Type, x.Required.ToString(), x.MultiValue.ToString(), x.Description })));

        if (includeOptions)
        {
            sheets.Append(Worksheet("Options", new[] { "FieldId", "OptionId", "Name", "Label", "Active" },
                snapshot.Options.Select(x => new[] { x.FieldId, x.OptionId, x.Name, x.Label, x.Active.ToString() })));
        }

        if (includeRaw)
        {
            sheets.Append(Worksheet("Raw", new[] { "Target", "Json" },
                new[] { new[] { snapshot.TargetType, snapshot.RawJson } }));
        }

        return "<?xml version=\"1.0\"?>" +
               "<?mso-application progid=\"Excel.Sheet\"?>" +
               "<Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" " +
               "xmlns:o=\"urn:schemas-microsoft-com:office:office\" " +
               "xmlns:x=\"urn:schemas-microsoft-com:office:excel\" " +
               "xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\">" +
               sheets +
               "</Workbook>";
    }

    private static string Worksheet(string name, string[] headers, IEnumerable<string[]> rows)
    {
        var builder = new StringBuilder();
        builder.Append($"<Worksheet ss:Name=\"{Xml(name)}\"><Table>");
        builder.Append(Row(headers));
        foreach (var row in rows)
        {
            builder.Append(Row(row));
        }
        builder.Append("</Table></Worksheet>");
        return builder.ToString();
    }

    private static string Row(IEnumerable<string> cells)
    {
        return "<Row>" + string.Concat(cells.Select(cell => $"<Cell><Data ss:Type=\"String\">{Xml(cell)}</Data></Cell>")) + "</Row>";
    }

    private static string Xml(string? value)
    {
        return (value ?? string.Empty)
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
    }
}

public sealed record BuildTaxonomyArtifactRequest(
    string TargetType,
    string CredentialSetId,
    bool IncludeOptions = true,
    bool IncludeRaw = true,
    string? ProjectId = null,
    string? FileName = null,
    string? Description = null);

public sealed record BuildTaxonomyArtifactResponse(
    ControlPlaneArtifactRecord Artifact,
    string TargetType,
    int FieldCount,
    int OptionCount,
    string FileName);

internal sealed record TaxonomySnapshot(
    string TargetType,
    List<TaxonomyField> Fields,
    List<TaxonomyOption> Options,
    string RawJson);

internal sealed record TaxonomyField(
    string FieldId,
    string Name,
    string Label,
    string Type,
    bool Required,
    bool MultiValue,
    string Description,
    string RawJson);

internal sealed record TaxonomyOption(
    string FieldId,
    string OptionId,
    string Name,
    string Label,
    bool Active,
    string RawJson);
