using System.Data;
using Migration.Connectors.Targets.Bynder.Clients;
using Migration.Connectors.Targets.Bynder.Models;
using Migration.Shared.Files;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;

namespace Migration.Connectors.Targets.Bynder.Taxonomy;

/// <summary>
/// Connector-owned Bynder taxonomy workbook generation.
/// This intentionally reuses the legacy MetapropertyOptionBuilderFactoryApi + ExcelWriter flow
/// so Admin.Api does not parse Bynder metaproperty JSON or write a parallel workbook format.
/// </summary>
public sealed class BynderTaxonomyWorkbookBuilder
{
    public const string MetadataPropertiesContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

    private readonly IMemoryCache _memoryCache;
    private readonly ILogger<BynderTaxonomyWorkbookBuilder> _logger;

    public BynderTaxonomyWorkbookBuilder(
        IMemoryCache memoryCache,
        ILogger<BynderTaxonomyWorkbookBuilder> logger)
    {
        _memoryCache = memoryCache ?? throw new ArgumentNullException(nameof(memoryCache));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task<BynderTaxonomyWorkbookResult> BuildMetadataPropertiesWorkbookAsync(
        string baseUrl,
        string clientId,
        string clientSecret,
        string scopes,
        CancellationToken cancellationToken = default)
    {
        var configuration = CreateBynderSdkConfiguration(baseUrl, clientId, clientSecret, scopes);
        cancellationToken.ThrowIfCancellationRequested();

        var metaProperties = await ReadMetaPropertiesAsync(configuration).ConfigureAwait(false);
        cancellationToken.ThrowIfCancellationRequested();

        var dataTables = BuildMetaPropertiesDataTables(metaProperties);
        var stream = ExcelWriter.WriteDataTables(dataTables);
        stream.Position = 0;

        var optionCount = metaProperties.Values.Sum(x => x.Options?.Count ?? 0);
        _logger.LogInformation(
            "Generated Bynder metadata properties workbook. FieldCount={FieldCount}, OptionCount={OptionCount}",
            metaProperties.Count,
            optionCount);

        return new BynderTaxonomyWorkbookResult(stream, metaProperties.Count, optionCount, "BynderMetadataPropertiesWorkbook");
    }

    public async Task<BynderTaxonomyWorkbookResult> BuildBlankMetadataTemplateWorkbookAsync(
        string baseUrl,
        string clientId,
        string clientSecret,
        string scopes,
        CancellationToken cancellationToken = default)
    {
        var configuration = CreateBynderSdkConfiguration(baseUrl, clientId, clientSecret, scopes);
        cancellationToken.ThrowIfCancellationRequested();

        var metaProperties = await ReadMetaPropertiesAsync(configuration).ConfigureAwait(false);
        cancellationToken.ThrowIfCancellationRequested();

        var dataTable = BuildBlankMetadataTemplateDataTable(metaProperties);
        var stream = ExcelWriter.WriteDataTable(dataTable);
        stream.Position = 0;

        var optionCount = metaProperties.Values.Sum(x => x.Options?.Count ?? 0);
        _logger.LogInformation(
            "Generated Bynder blank metadata template workbook. FieldCount={FieldCount}, OptionCount={OptionCount}",
            metaProperties.Count,
            optionCount);

        return new BynderTaxonomyWorkbookResult(stream, metaProperties.Count, optionCount, "BynderBlankMetadataTemplate");
    }

    private async Task<Dictionary<string, BynderMetaProperty>> ReadMetaPropertiesAsync(
        global::Bynder.Sdk.Settings.Configuration configuration)
    {
        // The legacy API factory does not use the constructor IBynderClient for lookup calls;
        // it creates BynderRestClient from the supplied SDK configuration. Keep the same flow
        // used by the working legacy console path.
        var metaFactoryApi = new MetapropertyOptionBuilderFactoryApi(bynderClient: default!, _memoryCache);
        return await metaFactoryApi.CreateMetapropertyLookupApi(configuration).ConfigureAwait(false);
    }

    private static global::Bynder.Sdk.Settings.Configuration CreateBynderSdkConfiguration(
        string baseUrl,
        string clientId,
        string clientSecret,
        string scopes)
    {
        if (string.IsNullOrWhiteSpace(baseUrl)) throw new ArgumentException("Bynder BaseUrl is required.", nameof(baseUrl));
        if (string.IsNullOrWhiteSpace(clientId)) throw new ArgumentException("Bynder ClientId is required.", nameof(clientId));
        if (string.IsNullOrWhiteSpace(clientSecret)) throw new ArgumentException("Bynder ClientSecret is required.", nameof(clientSecret));
        if (string.IsNullOrWhiteSpace(scopes)) throw new ArgumentException("Bynder Scopes is required.", nameof(scopes));

        return new global::Bynder.Sdk.Settings.Configuration
        {
            BaseUrl = new Uri(baseUrl.Trim(), UriKind.Absolute),
            ClientId = clientId.Trim(),
            ClientSecret = clientSecret.Trim(),
            Scopes = scopes.Trim()
        };
    }

    private static List<DataTable> BuildMetaPropertiesDataTables(Dictionary<string, BynderMetaProperty> metaProperties)
    {
        var metaPropertiesDataTable = CreateMetaPropertyDataTable();
        var optionDataTables = new List<DataTable>();

        foreach (var key in metaProperties.Keys)
        {
            var metaProperty = metaProperties[key];
            var rowArray = new List<object?>
            {
                metaProperty.Id,
                metaProperty.Name,
                metaProperty.Label,
                metaProperty.IsMultiSelect,
                metaProperty.IsRequired,
                metaProperty.IsFilterable,
                metaProperty.IsMainfilter,
                metaProperty.IsEditable,
                metaProperty.ZIndex,
                metaProperty.IsDisplayField,
                metaProperty.IsMultifilter,
                metaProperty.ShowInGridView,
                metaProperty.ShowInListView,
                metaProperty.IsApiField,
                metaProperty.ShowInDuplicateView,
                metaProperty.Type,
                metaProperty.IsSearchable,
                metaProperty.IsDrilldown,
                metaProperty.UseDependencies
            };

            if (metaProperty.Options != null && metaProperty.Options.Count > 0)
            {
                var metaPropertyOptionsDataTable = CreateMetaPropertyOptionsDataTable(metaProperty.Name);

                foreach (var metaPropertyOption in metaProperty.Options)
                {
                    var rowOptionArray = new List<object?>
                    {
                        metaPropertyOption.Id,
                        metaPropertyOption.Name,
                        metaPropertyOption.Label,
                        metaPropertyOption.ZIndex,
                        metaPropertyOption.IsSelectable,
                        metaPropertyOption.LinkedOptionIds == null ? string.Empty : string.Join("|", metaPropertyOption.LinkedOptionIds)
                    };

                    metaPropertyOptionsDataTable.Rows.Add(rowOptionArray.ToArray());
                }

                optionDataTables.Add(metaPropertyOptionsDataTable);
            }

            metaPropertiesDataTable.Rows.Add(rowArray.ToArray());
        }

        var dataTables = new List<DataTable> { metaPropertiesDataTable };
        dataTables.AddRange(optionDataTables);
        return dataTables;
    }

    private static DataTable BuildBlankMetadataTemplateDataTable(Dictionary<string, BynderMetaProperty> metaProperties)
    {
        var dataTable = new DataTable("Metadata");

        dataTable.Columns.Add("Id");
        dataTable.Columns.Add("Name");

        foreach (var metaProperty in metaProperties.Values.OrderBy(x => x.ZIndex).ThenBy(x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var columnName = metaProperty.Name;
            if (!string.IsNullOrWhiteSpace(columnName) && !dataTable.Columns.Contains(columnName))
            {
                dataTable.Columns.Add(columnName);
            }
        }

        return dataTable;
    }

    private static DataTable CreateMetaPropertyDataTable()
    {
        var dataTable = new DataTable("MetaProperties");
        dataTable.Columns.Add("Id");
        dataTable.Columns.Add("Name");
        dataTable.Columns.Add("Label");
        dataTable.Columns.Add("IsMultiSelect");
        dataTable.Columns.Add("IsRequired");
        dataTable.Columns.Add("IsFilterable");
        dataTable.Columns.Add("IsMainfilter");
        dataTable.Columns.Add("IsEditable");
        dataTable.Columns.Add("ZIndex");
        dataTable.Columns.Add("IsDisplayField");
        dataTable.Columns.Add("IsMultiFilter");
        dataTable.Columns.Add("ShowInGridView");
        dataTable.Columns.Add("ShowInListView");
        dataTable.Columns.Add("IsApiField");
        dataTable.Columns.Add("ShowInDuplicateView");
        dataTable.Columns.Add("Type");
        dataTable.Columns.Add("IsSearchable");
        dataTable.Columns.Add("IsDrilldown");
        dataTable.Columns.Add("UseDependencies");
        return dataTable;
    }

    private static DataTable CreateMetaPropertyOptionsDataTable(string nameOfMetaProperty)
    {
        var dataTable = new DataTable(string.IsNullOrWhiteSpace(nameOfMetaProperty) ? "Options" : nameOfMetaProperty);
        dataTable.Columns.Add("Id");
        dataTable.Columns.Add("Name");
        dataTable.Columns.Add("Label");
        dataTable.Columns.Add("ZIndex");
        dataTable.Columns.Add("IsSelectable");
        dataTable.Columns.Add("LinkedOptionIds");
        return dataTable;
    }
}

public sealed record BynderTaxonomyWorkbookResult(
    MemoryStream Stream,
    int FieldCount,
    int OptionCount,
    string WorkbookKind);
